apiVersion: v2
name: PlaneAlert
description: PlaneAlert Helm Chart

type: application

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 11.6.18
    repository: https://charts.bitnami.com/bitnami

