version: '3.7'

services:

  planealert:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/home/pptruser/app/config
    restart: unless-stopped
    security_opt:
      - seccomp=chrome.json
