version: '3.7'

services:

  planealert:
    image: ghcr.io/nfacha/planealert:2.0
    volumes:
      - ./config:/home/pptruser/app/config
    restart: unless-stopped
    security_opt:
      - seccomp=chrome.json
