version: '3.7'

services:

  planealert:
    build: '.'
    volumes:
      - ./config:/home/pptruser/app/config
    restart: unless-stopped
    security_opt:
      - seccomp=chrome.json
    cap_add:
      - SYS_ADMIN
