version: '3'

services:

  planealert:
    image: ghcr.io/nfacha/planealert:dev
    volumes:
      - ./config:/home/pptruser/app/config
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: "3g"
    security_opt:
      - seccomp=chrome.json
