version: '3.7'

services:

  planealert:
    image: ghcr.io/nfacha/planealert:dev
    volumes:
      - ./config:/home/pptruser/app/config
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 3G
    security_opt:
      - seccomp=chrome.json
    cap_add:
      - SYS_ADMIN
