apiVersion: apps/v1
kind: Deployment
metadata:
  name: planealert
  namespace: {{.Release.Namespace}}
  labels:
    app: planealert
spec:
  selector:
    matchLabels:
      app: planealert
  replicas: 1
  template:
    metadata:
      labels:
        app: planealert
    spec:
      containers:
        - name: planealert
          image: "ghcr.io/nfacha/planealert:master"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /app/config.json
              name: plane-alert-config
              subPath: config.json
      volumes:
        - name: plane-alert-config
          configMap:
            name: plane-alert-config
