config:
  lastSeen: null
  onGround: false
  liveTrack: false
  lat: null
  lon: null
  alt: null
name: Test
icao: 49516B
registration: CS-TKK
allowedAirports:
  - large_airport
  - medium_airport
  - small_airport
refreshInterval: 60
