config:
  lastSeen: 1660419307205
  onGround: true
  liveTrack: false
  squawk: ""
  lat: 51.477608
  lon: -0.460479
  alt: 0
fileName: 495247.yaml
name: Test
icao: XXXX
registration: D-AIJB
allowedAirports:
  - large_airport
  - medium_airport
  - small_airport
refreshInterval: 60
