config:
  lastSeen: 1660419833683
  onGround: false
  liveTrack: true
  squawk: "2013"
  lat: 51.437256
  lon: -0.316599
  alt: 4150
notifications:
  discord:
    enabled: false
    webhooks: []
fileName: 495247.yaml
name: Test
icao: 4008B1
registration: D-AIJB
allowedAirports:
  - large_airport
  - medium_airport
  - small_airport
refreshInterval: 60
