meta:
  lastSeen: 1660424369606
  onGround: false
  liveTrack: true
  squawk: "3461"
  lat: 51.403107
  lon: -0.089969
  alt: 6050
notifications:
  includeScreenshots: true
  discord:
    enabled: false
    webhooks: []
  twitter:
    enabled: true
    accounts:
      - username: PlaneAlert
        accessToken: ""
        accessSecret: ""
fileName: 495247.yaml
name: Test
icao: "406E10"
registration: D-AIJB
allowedAirports:
  - large_airport
  - medium_airport
  - small_airport
refreshInterval: 60
