config:
  lastSeen: 1660416166610
  onGround: true
  liveTrack: true
  squawk: "2023"
  lat: 51.464802
  lon: -0.483918
  alt: 0
fileName: 495247.yaml
name: Test
icao: 407844
registration: G-NEOZ
allowedAirports:
  - large_airport
  - medium_airport
  - small_airport
refreshInterval: 60
