meta:
  lastSeen: 1660422620874
  onGround: false
  liveTrack: true
  squawk: "6307"
  lat: 49.008799
  lon: 0.356767
  alt: 35050
notifications:
  includeScreenshots: true
  discord:
    enabled: true
    webhooks:
      - https://discordapp.com/api/webhooks/1008076795624554677/DRMcT8QDEriIJG028lxDc1Ww9tvB0gAlEeTLqcyUcjseOuIMDKghDCf7BAj_r1TczV5b
fileName: 495247.yaml
name: Test
icao: 40624F
registration: D-AIJB
allowedAirports:
  - large_airport
  - medium_airport
  - small_airport
refreshInterval: 60
